# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "composer"
    target-branch: "main"
    directory: "/"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "composer"
    labels:
      - "php dependency"
    ignore:
      - dependency-name: "symfony/framework-bundle"
        versions: ["5.x", "6.x"]
      - dependency-name: "symfony/dotenv"
        versions: ["5.x", "6.x"]
      - dependency-name: "symfony/yaml"
        versions: ["5.x", "6.x"]
      - dependency-name: "symfony/phpunit-bridge"
        versions: ["5.x", "6.x"]
      - dependency-name: "symfony/browser-kit"
        versions: ["5.x", "6.x"]
      - dependency-name: "symfony/css-selector"
        versions: ["5.x", "6.x"]


  #
  # Tools dependecy track
  #
  - package-ecosystem: "composer"
    target-branch: "main"
    directory: "/tools/phpstan"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 5
    schedule:
      interval: "daily"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "composer"
    labels:
      - "tool dependency"

  - package-ecosystem: "composer"
    target-branch: "main"
    directory: "/tools/psalm"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 5
    schedule:
      interval: "daily"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "composer"
    labels:
      - "tool dependency"

  - package-ecosystem: "composer"
    target-branch: "main"
    directory: "/tools/ecs"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 5
    schedule:
      interval: "daily"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "composer"
    labels:
      - "tool dependency"
