doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: '13'

        types:
            job_id: Ingesting\PublicJob\Adapter\Persistence\Doctrine\Config\JobIdType
            errata_id: Ingesting\Errata\Adapter\Persistence\Doctrine\Config\ErrataIdType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

            PubicJob:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/core/ingesting/src/PublicJob/Adapter/Persistence/Doctrine/Config/Yaml'
                prefix: 'Ingesting\PublicJob\Application\Model'
                alias: PublicJob

            ErrataFeed:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/core/ingesting/src/Errata/Adapter/Persistence/Doctrine/Config/Yaml'
                prefix: 'Ingesting\Errata\Application\Model'
                alias: ErrataFeed
