# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # the IP address (or range) of your proxy
    #trusted_proxies: '192.0.0.1,10.0.0.0/8'

    trusted_proxies: '127.0.0.1,REMOTE_ADDR'
    # trust *all* "X-Forwarded-*" headers
    #trusted_headers: [ 'x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix' ]
    # or, if your proxy instead uses the "Forwarded" header
    trusted_headers: [ 'forwarded' ]

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

#    assets:
#        packages:
#            backofficeAppConfig:
#                json_manifest_path: '%kernel.project_dir%/public/build-backoffice/manifest.json'
#            frontAppConfig:
#                json_manifest_path: '%kernel.project_dir%/public/build-front/manifest.json'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
