twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/templates': 'main'
        '%kernel.project_dir%/core/publishing/templates': 'front'
        '%kernel.project_dir%/core/publishing/src/Cms/Adapter/HttpWeb/Templates': 'cms'
        '%kernel.project_dir%/core/backoffice/src/Adapter/HttpWeb/Templates': 'backoffice'
        '%kernel.project_dir%/core/websiteBFF/src/Adapter/HttpWeb/Templates': 'website'

    form_themes: ['bootstrap_5_horizontal_layout.html.twig','@FOSCKEditor/Form/ckeditor_widget.html.twig']


when@test:
    twig:
        strict_variables: true
