twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/templates': 'main'
        '%kernel.project_dir%/core/publishing/templates': 'front'
        '%kernel.project_dir%/core/backoffice/templates': 'backoffice'


when@test:
    twig:
        strict_variables: true
