twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/templates': 'main'
        '%kernel.project_dir%/core/publishing/templates': 'front'
        '%kernel.project_dir%/core/publishing/src/Cms/Adapter/HttpWeb/Templates': 'cms'
        '%kernel.project_dir%/core/backoffice/templates': 'backoffice'

    form_themes: ['bootstrap_5_horizontal_layout.html.twig']


when@test:
    twig:
        strict_variables: true
