version: '3.8'

services:
  app:
    build:
      context: ./docker/development/php
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "2222:22"
      - "9021:9021"
    volumes:
      - "./:/app"
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
#      PHP_DEBUGGER: xdebug
#      XDEBUG_MODE: coverage
#      XDEBUG_REMOTE_AUTOSTART: 1
#      XDEBUG_REMOTE_CONNECT_BACK: 1
#      # IMPORTANT: please change this ip address to your docker host ip. Get your docker host ip:
#      # docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' docker_php_1
#      #- XDEBUG_REMOTE_HOST=172.19.0.1
#      XDEBUG_REMOTE_PORT: 9021


  web:
    image: nginx:1.22-alpine
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - "./:/app"
      - ./docker/development/nginx/default.conf:/etc/nginx/conf.d/default.conf
#    environment:
#      WEB_DOCUMENT_ROOT: /app/public
#      WEB_DOCUMENT_INDEX: index.php
#      WEB_PHP_SOCKET: app:9000

  database:
    image: mysql:${MYSQL_VERSION:-8.0}
#    networks:
#      - default
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: ${MYSQL_DB:-db-name}
      MYSQL_USER: ${MYSQL_USER:-db-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-db-password}
    ports:
      - "3306:3306"

  database-test:
    image: mysql:${MYSQL_VERSION:-8.0}
    ports:
      - "3306"
      - "3307:3306" ###--- used by behat (local execution against docker)
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: ${MYSQL_DB:-db-name_test}
      MYSQL_USER: ${MYSQL_USER:-db-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-db-password}
      # volumes:
      # - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    ports:
      - '81:80'
#    networks:
#      - default
    depends_on:
      - database
      - database-test
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: docker
      PMA_HOST: database

  encore:
    image: node:16
    environment:
      USER: node
    working_dir: /app
    volumes:
      - .:/app
    command: ["yarn", "encore", "dev", "--watch" ]


