version: '3.8'

services:
  php:
    image: ghcr.io/medicalmundi/${PHP_RELEASE_CANDIDATE_IMAGE_NAME:-internal-php-rc}:${RELEASE_CANDIDATE_TAG:-main}
    depends_on:
      - pgsql
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      APP_ENV: ${APP_ENV:-prod}
      APP_SECRET: 9efe3211a261ad2a84eb847aa045ffc2
      DATABASE_URL: "postgresql://ci-db-user:ci-db-password@pgsql:5432/ci-db-name?serverVersion=13&charset=utf8"

  nginx:
    image: webdevops/nginx:alpine
    depends_on:
      - php
    ports:
      # HTTP
      - target: 80
        published: 80
        protocol: tcp
      # HTTPS
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - "./:/app"
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      WEB_PHP_SOCKET: php:9000


  pgsql:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    ports:
      - "5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-ci-db-name}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ci-db-password}
      POSTGRES_USER: ${POSTGRES_USER:-ci-db-user}
