version: '3.8'

services:
  php:
    image: webdevops/php-dev:7.4
    ports:
      - "9021:9021"
      - "2222:22"
    working_dir: /app
    user: application
    volumes:
      - "./:/app"
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      PHP_DEBUGGER: xdebug
      XDEBUG_MODE: coverage
      XDEBUG_REMOTE_AUTOSTART: 1
      XDEBUG_REMOTE_CONNECT_BACK: 1
      # IMPORTANT: please change this ip address to your docker host ip. Get your docker host ip:
      # docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' docker_php_1
      #- XDEBUG_REMOTE_HOST=172.19.0.1
      XDEBUG_REMOTE_PORT: 9021


  nginx:
    image: webdevops/nginx:alpine
    ports:
      - "8088:80"
    volumes:
      - "./:/app"
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      WEB_PHP_SOCKET: php:9000


  pgsql:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    ports:
      - "5432"
    links:
      - pgadmin
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
      # volumes:
      # - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw


  pgadmin:
    image: dpage/pgadmin4:6.2
    ports:
      - "8181:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"


  pgsql-test:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    ports:
      - "5432"
    links:
      - pgadmin
    environment:
      POSTGRES_DB: ${POSTGRES_TEST_DB:-app_test}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_TEST_USER:-symfony}
      # volumes:
      # - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
