version: '3.8'

services:
  app:
    image: webdevops/php-dev:7.4
    ports:
      - "2222:22"
      - "9021:9021"
    volumes:
      - "./:/app"
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      PHP_DEBUGGER: xdebug
      XDEBUG_MODE: coverage
      XDEBUG_REMOTE_AUTOSTART: 1
      XDEBUG_REMOTE_CONNECT_BACK: 1
      # IMPORTANT: please change this ip address to your docker host ip. Get your docker host ip:
      # docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' docker_php_1
      #- XDEBUG_REMOTE_HOST=172.19.0.1
      XDEBUG_REMOTE_PORT: 9021

  web:
    image: webdevops/nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - "./:/app"
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      WEB_PHP_SOCKET: app:9000


  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    ports:
      - "5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-db-name}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-db-password}
      POSTGRES_USER: ${POSTGRES_USER:-db-user}
      # volumes:
      # - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw


  database-test:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    ports:
      - "5432"
    environment:
      POSTGRES_DB: ${POSTGRES_TEST_DB:-db-name_test}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD:-db-password}
      POSTGRES_USER: ${POSTGRES_TEST_USER:-db-user}
      # volumes:
      # - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw


  pgadmin:
    image: dpage/pgadmin4:6.2
    ports:
      - "8181:80"
    depends_on:
      - database
      - database-test
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"

  encore:
    image: node:16-alpine
    container_name: encore
    environment:
      USER: node
      PYTHON: python3
    working_dir: /app
    volumes:
      - .:/app
    command: ["yarn", "encore", "dev", "--watch" ]


