version: '3.8'

services:
  php:
    image: ghcr.io/medicalmundi/internal-php-rc:${MEMU_JOB_VERSION:-main}
    depends_on:
      - pgsql
    ports:
      - "9021:9021"
#    volumes:
#      - "./:/app"
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
#      PHP_DEBUGGER: xdebug
#      XDEBUG_MODE: coverage
#      XDEBUG_REMOTE_AUTOSTART: 1
#      XDEBUG_REMOTE_CONNECT_BACK: 1
#      # IMPORTANT: please change this ip address to your docker host ip. Get your docker host ip:
#      # docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' docker_php_1
#      #- XDEBUG_REMOTE_HOST=172.19.0.1
#      XDEBUG_REMOTE_PORT: 9021

  php-nginx:
    image: webdevops/php-nginx:7.4
#    build:
#      context: .
#      dockerfile: docker/webdevilops/php-nginx/Dockerfile
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - "./:/app"
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      WEB_PHP_SOCKET: php:9000


  pgsql:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    ports:
      - "5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    # volumes:
      # - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
