version: '3.8'

services:
  php:
    image: ghcr.io/medicalmundi/internal-php-rc:${MEMU_JOB_VERSION:-main}
    depends_on:
      - pgsql
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      APP_ENV: dev
      APP_SECRET: 9efe3211a261ad2a84eb847aa045ffc2
      DATABASE_URL: "postgresql://symfony:ChangeMe@127.0.0.1:5432/app?serverVersion=13&charset=utf8"

  nginx:
    image: webdevops/nginx:alpine
    depends_on:
      - php
    ports:
      # HTTP
      - target: 80
        published: 80
        protocol: tcp
      # HTTPS
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - "./:/app"
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      WEB_PHP_SOCKET: php:9000


  pgsql:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    ports:
      - "5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-ci-db-name}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ci-db-password}
      POSTGRES_USER: ${POSTGRES_USER:-ci-db-user}
