controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

publishing_controllers:
    resource: ../../core/publishing/src/Cms/Adapter/HttpWeb/
    type: annotation

publishing_api_controllers:
    resource: ../../core/publishing/src/Cms/Adapter/HttpApi/
    type: annotation

backoffice_controllers:
    resource: ../../core/backoffice/src/Adapter/HttpWeb/
    type: annotation

backoffice_api_controllers:
    resource: ../../core/backoffice/src/Adapter/HttpApi/
    type: annotation

ingesting_controllers:
    resource: ../../core/ingesting/src/PublicJob/Adapter/HttpWeb/
    type: annotation
