<?php declare(strict_types=1);

namespace Ingesting\Tests\Unit\Errata\Usecase;

use Ingesting\Errata\Application\Domain\Model\ErrataFeed;
use Ingesting\Errata\Application\Domain\Model\ErrataFeedRepository;
use Ingesting\Errata\Application\Domain\Model\ErrataId;
use Ingesting\Errata\Application\Domain\Model\Service\ErrataUniqueService;
use Ingesting\Errata\Application\Usecase\CreateErrataFeedItemUsecase;
use Ingesting\SharedKernel\Model\PublicationDate;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

/**
 * @covers \Ingesting\Errata\Application\Usecase\CreateErrataFeedItemUsecase
 */
class CreateErrataFeedItemUsecaseTest extends TestCase
{
    private const ITEM_UUID = 'cc97e157-a0fa-478a-8ade-5692bbaa08e0';

    private const ITEM_TITLE = 'a title';

    private const ITEM_DESCRIPTION = 'a very long description, may be not';

    private const ITEM_LINK = 'https://www.google.it';

    private const ITEM_PUB_DATE = '2047-02-01 10:00:00';

    /**
     * @var ErrataFeedRepository & MockObject
     */
    private $repository;

    /**
     * @var ErrataUniqueService & MockObject
     */
    private $errataUniqueService;

    private CreateErrataFeedItemUsecase $usecase;

    protected function setUp(): void
    {
        $this->repository = $this->getMockBuilder(ErrataFeedRepository::class)->getMock();

        $this->errataUniqueService = $this->getMockBuilder(ErrataUniqueService::class)
            ->disableOriginalConstructor()
            ->getMock();

        $this->usecase = new CreateErrataFeedItemUsecase($this->repository, $this->errataUniqueService);
    }

    /**
     * @test
     */
    public function ShouldAddANewErrataFeedItem(): void
    {
        $errataId = ErrataId::fromString(self::ITEM_UUID);

        $this->errataUniqueService->expects(self::once())
            ->method('isUnique')
            ->willReturn(true)
        ;

        $this->repository->expects(self::once())
            ->method('save')
            ->with(
                self::callback(
                    function ($param) use ($errataId): bool {
                        if ($param instanceof ErrataFeed
                            && $param->id() === $errataId
                            && $param->title() === self::ITEM_TITLE
                            && $param->description() === self::ITEM_DESCRIPTION
                            && $param->publicationDate()->sameValueAs(PublicationDate::fromString(self::ITEM_PUB_DATE))
                            && $param->link() === self::ITEM_LINK
                        ) {
                            return true;
                        }
                        return false;
                    }
                )
            );

        $this->usecase->createErrataFeed(self::ITEM_TITLE, self::ITEM_DESCRIPTION, self::ITEM_LINK, self::ITEM_PUB_DATE, $errataId);
    }

    /**
     * @test
     */
    public function ShouldAddANewErrataFeedItemWithAutogeneratedIdentity(): void
    {
        $this->errataUniqueService->expects(self::once())
            ->method('isUnique')
            ->willReturn(true)
        ;

        $this->repository->expects(self::once())
            ->method('save')
            ->with(
                self::callback(
                    function ($param): bool {
                        if ($param instanceof ErrataFeed
                            && $param->title() === self::ITEM_TITLE
                            && $param->description() === self::ITEM_DESCRIPTION
                            && $param->publicationDate()->sameValueAs(PublicationDate::fromString(self::ITEM_PUB_DATE))
                            && $param->link() === self::ITEM_LINK

                        ) {
                            return true;
                        }
                        return false;
                    }
                )
            );

        $this->usecase->createErrataFeed(self::ITEM_TITLE, self::ITEM_DESCRIPTION, self::ITEM_LINK, self::ITEM_PUB_DATE);
    }

    /**
     * @test
     */
    public function shouldNotPersistDuplicatedItem(): void
    {
        $this->expectException(\RuntimeException::class);

        $this->errataUniqueService->expects(self::once())
            ->method('isUnique')
            ->willReturn(false)
            ;

        $this->repository->expects(self::never())
            ->method('save')
            ->withAnyParameters()
            ;

        $this->usecase->createErrataFeed(self::ITEM_TITLE, self::ITEM_DESCRIPTION, self::ITEM_LINK, self::ITEM_PUB_DATE);
    }
}
