# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    Ingesting\PublicJob\Adapter\Persistence\Doctrine\DoctrineJobFeedRepository:
        public: true

    Ingesting\PublicJob\Infrastructure\ProductionServiceContainer:
        arguments:
            - '@Ingesting\PublicJob\Adapter\Persistence\Doctrine\DoctrineJobFeedRepository'

    Ingesting\PublicJob\Application\PublicJobModule:
        factory: [ '@Ingesting\PublicJob\Infrastructure\ProductionServiceContainer', 'module' ]
        public: true

    Ingesting\PublicJob\Adapter\Cli\IngestingJobCommand:
        arguments:
            - '@Ingesting\PublicJob\Application\PublicJobModule'
        tags: ['console.command']

    Ingesting\PublicJob\Adapter\HttpWeb\:
        resource: '../core/ingesting/src/PublicJob/Adapter/HttpWeb/'
        tags: [ 'controller.service_arguments' ]

    Ingesting\PublicJob\Application\Usecase\ShowFeed\ShowAllFeedJob: '@Ingesting\PublicJob\Application\Usecase\ShowFeed\ShowFeedJobViewCase'
    Ingesting\PublicJob\Application\Usecase\ShowFeed\ShowFeedJobViewCase:

    Ingesting\PublicJob\Application\Usecase\ReadableJobFeedRepository: '@Ingesting\PublicJob\Adapter\Persistence\Doctrine\DoctrineReadableJobFeedRepository'
    Ingesting\PublicJob\Adapter\Persistence\Doctrine\DoctrineReadableJobFeedRepository:
        public: true

    Ingesting\PublicJob\AclAdapter\Repository\DistributableJobFeedRepository:
        public: true

    Ingesting\PublicJob\AclAdapter\InProcess\IngestingAclService:
        arguments:
            - '@Ingesting\PublicJob\AclAdapter\Repository\DistributableJobFeedRepository'




    Ingesting\Errata\Adapter\Persistence\Doctrine\DoctrineErrataFeedRepository:
        public: true

    Ingesting\Errata\Infrastructure\ProductionServiceContainer:
        arguments:
            - '@Ingesting\Errata\Adapter\Persistence\Doctrine\DoctrineErrataFeedRepository'

    Ingesting\Errata\Application\ErrataModule:
        factory: [ '@Ingesting\Errata\Infrastructure\ProductionServiceContainer', 'module' ]
        public: true

    Ingesting\Errata\Adapter\Cli\IngestingErrataCommand:
        arguments:
            - '@Ingesting\Errata\Application\ErrataModule'
        tags: ['console.command']



    #
    #   PUBLISHING BOUNDED CONTEXT
    #
    Publishing\:
        resource: '../core/publishing/src/'
        exclude:
            #- '../core/publishing/src/Cms/Application/Model'
            - '../core/publishing/src/Cms/Adapter/Persistence/DoctrineType'

    Publishing\Cms\Adapter\HttpWeb\:
        resource: '../core/publishing/src/Cms/Adapter/HttpWeb/'
        tags: [ 'controller.service_arguments' ]

    Publishing\Cms\Adapter\HttpApi\:
        resource: '../core/publishing/src/Cms/Adapter/HttpApi/'
        tags: [ 'controller.service_arguments' ]

    Publishing\Cms\Adapter\Persistence\DoctrineArticleRepository: ~



    #
    #   BACKOFFICE UI
    #
    Backoffice\:
        resource: '../core/backoffice/src/'
        exclude:
            - '../core/backoffice/src/Application/Model'

    Backoffice\Adapter\HttpWeb\:
        resource: '../core/backoffice/src/Adapter/HttpWeb/'
        tags: [ 'controller.service_arguments' ]

    Backoffice\Adapter\HttpApi\:
        resource: '../core/backoffice/src/Adapter/HttpApi/'
        tags: [ 'controller.service_arguments' ]



    #
    #   WEBSITE BFF BOUNDED CONTEXT
    #
    WebSiteBFF\:
        resource: '../core/websiteBFF/src/'

    WebSiteBFF\Adapter\HttpWeb\:
        resource: '../core/websiteBFF/src/Adapter/HttpWeb/'
        tags: [ 'controller.service_arguments' ]

    WebSiteBFF\Adapter\HttpApi\:
        resource: '../core/websiteBFF/src/Adapter/HttpApi/'
        tags: [ 'controller.service_arguments' ]

