name: Acceptance stage

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/5 * * * *'


env:
  GITHUB_PAT: ${{ secrets.MEMUJOB_CI_GHA_PAT }}
  PHP_RELEASE_CANDIDATE_IMAGE_NAME: internal-php-rc
  PHP_EXTENSIONS: ctype, curl, gd, iconv, intl, opcache, openssl, mbstring, mysql, pdo_sqlite
  PHP_EXTENSIONS_CACHE_KEY: cache-php-extensions-v1


jobs:
  detect-release-candidate:
    runs-on: ubuntu-18.04
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Login to GHCR
        id: docker_ghrc_login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  try-test:
    runs-on: ubuntu-18.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GHCR
        id: docker_ghrc_login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: List imgaes
        run: docker image ls

      - name: Start services
        run: docker-compose -f docker-compose.ci-gha.yaml up -d

#      - name: Wait for services
#        run: |
#          while status="$(docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" "$(docker-compose -f docker-compose.ci-gha.yaml ps -q php)")"; do
#            case $status in
#              starting) sleep 1;;
#              healthy) exit 0;;
#              unhealthy)
#                docker-compose -f docker-compose.ci-gha.yaml ps
#                docker-compose -f docker-compose.ci-gha.yaml logs
#                exit 1
#              ;;
#            esac
#          done
#          exit 1

      - name: services list
        run: docker-compose -f docker-compose.ci-gha.yaml ps

      - name: Check HTTP reachability (localhost)
        run: curl -v -o /dev/null http://localhost
        continue-on-error: false

#      - name: Check HTTP reachability (0.0.0.0)
#        run: curl -v -o /dev/null http://0.0.0.0
#        continue-on-error: false

      - name: Check HTTP reachability (127.0.0.1)
        run: curl -v -o /dev/null http://127.0.0.1
        continue-on-error: true

      - name: Check HTTP reachability (healcheck)
        run: curl -v -o /dev/null http://127.0.0.1/sys/healt/check
        continue-on-error: true

      - name: Check HTTPS reachability
        run: curl  -vk -o /dev/null https://127.0.0.1
        continue-on-error: true

      - name: Show application log
        run: |
          docker-compose -f docker-compose.ci-gha.yaml logs php
          docker-compose -f docker-compose.ci-gha.yaml exec -T php ls -al /app/var/log
          docker-compose -f docker-compose.ci-gha.yaml exec -T php ls -al /app/var/cache
        continue-on-error: true

      - name: Doctrine Schema Validator
        run: docker-compose -f docker-compose.ci-gha.yaml exec -T php bin/console doctrine:schema:validate --skip-sync
        continue-on-error: true

      - name: Stop services
        run: docker-compose -f docker-compose.ci-gha.yaml down