name: Architecture check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  architecture-check:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-progress
        composer bin deptrac install

    - name: Run core analysis Context To Context
      run: vendor/bin/deptrac analyse core/depfile-core.yaml

    - name: Run core analysis Job Context
      run: vendor/bin/deptrac analyse core/depfile-publicjob.yaml

    - name: Run core analysis Errata Context
      run: vendor/bin/deptrac analyse core/depfile-errata.yaml

    - name: Run core analysis Analyzer Context
      run: vendor/bin/deptrac analyse core/depfile-analyzer.yaml
