# see https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions

name: Publish coverage report to codecov

on:
  repository_dispatch:
    types: [code-coverage-report-was-completed-successfully]

env:
  GITHUB_PAT: ${{ secrets.MEMUJOB_CI_GHA_PAT }}
  REPORT_FOLDER_PHPUNIT: ${{ secrets.REPORT_FOLDER_PHPUNIT }}
  PHPUNIT_ARTIFACT_NAME: ${{ secrets.CI_ENV_PHPUNIT_ARTIFACT_NAME }}

jobs:

  publish-coverage-report:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Reveal GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - run: ls -al

      - name: Login to gh
        run: |
          gh run download -n ${{ env.PHPUNIT_ARTIFACT_NAME }}-${{ env.GITHUB_SHA }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - run: ls -al artifact-data/



