name: Coding standard

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ecs:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-progress
        composer bin ecs install

    - name: Run easy-coding-standard
      run: vendor/bin/ecs check
