name: Delete package

on:
  workflow_dispatch:
    inputs:
      packageName:
        description: 'Name of the package.'
        required: true
        default: 'a-package-name'

env:
  GITHUB_PAT: ${{ secrets.MEMUJOB_CI_GHA_PAT }}

jobs:
  delete-package:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          echo "Image Name: ${{ github.event.inputs.packageName }}"

      - name: Reveal env vars
        run: |
          echo GITHUB_WORKFLOW   = $GITHUB_WORKFLOW
          echo HOME              = $HOME
          echo GITHUB_ACTION     = $GITHUB_ACTION
          echo GITHUB_ACTIONS    = $GITHUB_ACTIONS
          echo GITHUB_ACTOR      = $GITHUB_ACTOR
          echo GITHUB_REPOSITORY = $GITHUB_REPOSITORY
          echo GITHUB_REPOSITORY_OWNER = $GITHUB_REPOSITORY_OWNER
          echo GITHUB_EVENT_NAME = $GITHUB_EVENT_NAME
          echo GITHUB_EVENT_PATH = $GITHUB_EVENT_PATH
          echo GITHUB_WORKSPACE  = $GITHUB_WORKSPACE
          echo GITHUB_SHA        = $GITHUB_SHA
          echo GITHUB_REF        = $GITHUB_REF


      - name: Delete package (curl version)
        run: |
          curl \
            -X DELETE \
            -H "Accept: application/vnd.github.v3+json" \
            -v -H "Authorization: token ${{ secrets.MEMUJOB_CI_GHA_PAT }}" https://api.github.com/repos/${{ env.GITHUB_REPOSITORY }} \
            https://api.github.com/orgs/medicalmundi/packages/container/${{ github.event.inputs.packageName }}