# see https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions

name: Publish metrics to codecov

on:
  repository_dispatch:
    types: [coverage-report-was-ready]

env:
  GITHUB_PAT: ${{ secrets.MEMUJOB_CI_GHA_PAT }}
  REPORT_FOLDER_PHPUNIT: 'coverage-report'
  PHPUNIT_ARTIFACT_NAME: 'phpunit-artifact'

jobs:

  publish-coverage-report:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Reveal GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Download Phpunit coverage artifact
        id: download-artifact
        run: |
          ls -al
          gh run download -n ${{ env.PHPUNIT_ARTIFACT_NAME }}-${{ env.GITHUB_SHA }}
          ls -al artifact-data/
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Upload coverage results to Codecov
        if: ${{ (steps.download-artifact.outcome == 'success')}}
        uses: codecov/codecov-action@v1
        with:
          directory: artifact-data/
          files: artifact-data/unit-test-clover.xml, artifact-data/integration-test-clover.xml
          name: phpunit-core-test
          #flags: unit-test
          fail_ci_if_error: false
        continue-on-error: true





