name: Build PHP base image

on:
  workflow_dispatch:
    inputs:
      phpVersion:
        description: 'PHP version'
        required: true
        default: '7.4-fpm-alpine3.14'
      imageName:
        description: 'Artifact image name'
        required: true
        default: 'internal-php-rc'
      imageTag:
        description: 'Artifact image tag'
        required: true
        default: 'base-v0.1.0'
      imageLabel:
        description: 'Artifact image label'
        required: false

jobs:
  build-php-base-artifact:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Image Name: ${{ github.event.inputs.imageName }}"
          echo "Image Tag: ${{ github.event.inputs.imageTag }}"
          echo "Image Label: ${{ github.event.inputs.iamgeLabel }}"

      - uses: actions/checkout@v2

      - run: sudo chown runner:docker /var/run/docker.sock
        if: ${{ env.ACT }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/medicalmundi/${{ github.event.inputs.imageName }}
            ghcr.io/medicalmundi/memu-job-rc
          # generate Docker tags based on the following events/attributes
          tags: |
            ${{ github.event.inputs.imageTag }}
          labels: ${{ steps.meta.outputs.imageLabel }}

      - name: Login to GHCR
        id: docker_ghrc_login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/php-base/Dockerfile
          #platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          push: true
          load: false
          no-cache: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}